name: zxbase_app
description: "Multiplatform Zxbase application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0+100

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_linkify: ^6.0.0
  flutter_riverpod: ^2.6.0
  flutter_typeahead: ^5.0.0
  flutter_webrtc: ^1.0.0
  path_provider: ^2.0.0
  socket_io_client: ^3.0.0
  url_launcher: ^6.0.0
  uuid: ^4.0.0
  zxcvbn: ^1.0.0

  zxbase_api_client:
    git: https://github.com/zxbase/zxbase_api_client
  zxbase_crypto:
    git: https://github.com/zxbase/zxbase_crypto
  zxbase_flutter_ui:
    git: https://github.com/zxbase/zxbase_flutter_ui
  zxbase_model:
    git: https://github.com/zxbase/zxbase_model
  zxbase_vault:
    git: https://github.com/zxbase/zxbase_vault

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
